---
title: "Dev"
author: "Akshay Kulkarni"
date: "2/23/2020"
output: html_document
---


## R Markdown


```{r}
library(dplyr)


splitCombinedData  <-  function(inputdata, column, head_rows=5){
  if (class(inputdata$column) == "factor") {
    opts <- levels(inputdata$column)
  }
  else{
    opts <- inputdata %>% select(column) %>% distinct()
  }

  guide <- list()
  test <- list()
  i <- 1
  for (val in opts){
    guide[[i]] <- inputdata[inputdata$column == val, ][c(1:5), ]
    test[[i]] <- inputdata[inputdata$column == val, ][-c(1:5), ]
    i <- i+1
  }

  guide <- bind_rows(guide)
  test <-  bind_rows(test)
  
  print(guide)
  
  split_df <- list(guide, test)
  
  return(split_df)
}


test <- splitCombinedData(combined_data,"Precursor")
#########################

combined_data <-  read.csv("Datasets/Sampledata_CPTAC_Study_9_1_Site54 copy.csv")
opts <- levels(combined_data$"Precursor")
write.csv(
  bind_rows(
  lapply(opts, function(x) combined_data[combined_data$"Precursor" == x, ][c(1:5), ] ))
  ,"Sampledata_CPTAC_Study_9_1_Site54_GUIDE.csv")


write.csv(
  bind_rows(
  lapply(opts, function(x) combined_data[combined_data$"Precursor" == x, ][-c(1:5), ] ))
  ,"Sampledata_CPTAC_Study_9_1_Site54_TEST.csv")

```
```{r}
library(plotly)
library(dplyr)
library(tidyr)


source('src/QCMetrics.R')
source('src/ggradar.R')
source('src/helper-functions.R')


test <- read.csv("./Datasets/Sampledata_CPTAC_Study_9_1_Site54_GUIDE.csv", stringsAsFactors = T)


metrics <- c(find_custom_metrics(test))

peptides <- c(levels(test$Precursor))

dat2 <- test %>% filter(Precursor == peptides[[1]]) %>% mutate_at(metrics, ~(scale(., center = T) %>% as.vector)) 

dat3 <-  dat2 %>% select(Precursor,metrics) %>% pivot_longer(-Precursor, names_to = "Metric", values_to = "Value") 

temp <- test %>% select(Precursor,metrics) %>% pivot_longer(-Precursor, names_to = "Metric", values_to = "Value")

fig <- plot_ly(dat3, x = ~Metric, y = ~Value, color = ~Metric, type = "box")

fig

peptide_box.plot <- function(prodata, data.peptides, data.metrics, ret_obj_list = T) {
  plots <- list()
  for(i in seq_len(length(data.peptides))) {
    peptide <- data.peptides[i]
    
    data <- prodata %>% filter(Precursor == peptide) 
    
    data <-  data %>% mutate_at(data.metrics, ~(scale(., center = T) %>% as.vector)) 
    
    data <-  data %>% select(Precursor,data.metrics) %>% pivot_longer(-Precursor, names_to = "Metric", values_to = "Value") 
    
    plots[[i]] <- plot_ly(data, x = ~Metric, y = ~Value, color = ~Metric, type = "box") %>%
      layout(
        annotations = list(
          list(x = 0.5 , y = 1, text = peptide, showarrow = F, xref='paper', yref='paper')
        ),showlegend = FALSE)
  }
  
  if (ret_obj_list == F){
    height <- (length(data.peptides))*300
    p <- do.call(subplot,c(plots,nrows= floor(length(plots)/2))) %>%
      layout(autosize = TRUE, height = height,margin = unit(c(3, 1, 1, 1), "lines"))
    return(p)}
  else{
    return(plots)
  }
}


p <-  peptide_box.plot(test, peptides, metrics)


ggplotly(p[[1]])

```


```{r}
source('src/QCMetrics.R')
source('src/ggradar.R')
source('src/helper-functions.R')
source("src/data-validation.R")


library(h2o)
library(plotly)
library(dplyr)
library(tidyr)
library(RecordLinkage)
library(ggfortify)

h2o.shutdown()
# h2o.init()
h2oServer = h2o.init(ip = "localhost", port = 54321, max_mem_size = "5g", nthreads = -1 )
h2o.removeAll() # Removes all data from h2o cluster, ensuring it is clean.
h2o.no_progress()  # Turn off progress bars for notebook readability

# Setting H2O timezone for proper date data type handling
#h2o.getTimezone() ===>>> UTC
#h2o.listTimezones() # We can see all H2O timezones
h2o.setTimezone("US/Central")


# input_df <- read.csv("./Datasets/Sampledata_CPTAC_Study_9_1_Site54.csv")
input_df <- read.csv("./Datasets/SimData.csv")



 x <- dplyr::select_if(input_df, is.numeric)

df_unscaled <- input_checking(input_df)


write.csv(df_unscaled[df_unscaled$Precursor=="LVNELTEFAK",c(6:9)],"anomaly.csv")
metrics <- c(find_custom_metrics(df_unscaled))

# df <- df_unscaled %>% group_by(Precursor) %>% mutate_at(metrics, ~(scale(., center = T) %>% as.vector)) 

LVN <- df_unscaled %>% filter(Precursor == "LVNELTEFAK")


# LVN <- LVN %>% group_by(Precursor) %>% mutate_at(metrics, ~(scale(., center = T) %>% as.vector))

LVN <- LVN[6:9]

allData_hex = as.h2o( LVN )

# LVN <- df %>% filter(Precursor == "LVNELTEFAK") %>% select(metrics)


# Import the dataset
CPTAC_full <- as.h2o(LVN,destination_frame = "CPTAC_full")

# Split dataset giving the training dataset 75% of the data
CPTAC_split <- h2o.splitFrame(data=CPTAC_full, ratios=0.75)

# Create a training set from the 1st dataset in the split
train <- CPTAC_split[[1]]

View(as.data.frame(train))
# Create a testing set from the 2nd dataset in the split
test <- CPTAC_split[[2]]

# Build an Isolation forest model

model <- h2o.isolationForest(training_frame=CPTAC_full,
                             sample_rate = 0.8,
                             ntrees = 100,
                             seed= 123, 
                          )

# Calculate score
score_h2oObj <- h2o.predict(model, CPTAC_full)

score <-  as.data.frame(score_h2oObj)

result_pred <- score$predict

result_ml <- score$mean_length

head(score,20)

hist(result_ml)

qplot(result_pred, geom="histogram") 

conf <-  0.98

thresh <-  quantile(score$predict,conf)

Outliers <- score[score$predict>thresh,]

Outliers1 <- score_h2oObj[score_h2oObj$predict>thresh,]

print(Outliers)

# Predict the leaf node assignment
# ln_pred <- h2o.predict_leaf_node_assignment(model, test)

# LVN$Anomaly_Score =  result_pred
# df <- LVN %>% mutate(Anomaly_Label = if_else(Anomaly_Score > thresh, 'Anomaly', 'Normal') )

test_lvn <- as.data.frame(CPTAC_full)

test_lvn$Anomaly_Score =  result_pred

test_lvn <- test_lvn %>% mutate(Anomaly_Label = if_else(Anomaly_Score > thresh, 'Anomaly', 'Normal') )


# apply PCA - scale. = TRUE is highly
# advisable, but default is FALSE.

LVN_red <-df[metrics]
df$Anomaly_Label <- as.factor(df$Anomaly_Label)

df.pca <- prcomp(LVN[1:4],
                 center = T,
                 scale. = T)

autoplot(df.pca, data = LVN, colour= 'RESPONSE')

summary(df.pca)
plot(df.pca, type = "l")

cols <- colnames(df)
predictors <- head(cols, length(cols)-2)
response <- tail(cols,1)



df_h2o <- as.h2o(df,destination_frame = "df_h2o")

df_h2o_split <- h2o.splitFrame(data=df_h2o, ratios=0.75)

df_train <- df_h2o_split[[1]]

df_test <- df_h2o_split[[2]]


anomaly_classificationtree = h2o.randomForest(x = metrics, y = response, 
                        training_frame = df_train,
                        ntrees = 1, min_rows = 1, sample_rate = 1,            
                        max_depth = 5,
                        seed = 1)


print(df_train)
```

```{r}


test <- prcomp(LVN,center = T,
                 scale. = T)
info <-  summary(test)

info$importance
info$importance[2]

x <- as.vector(test[["x"]][,1])
y <- as.vector(test[["x"]][,2])
z <- as.vector(test[["x"]][,3])


anom <- as.vector(score$predict)

testdf <-  as.data.frame(cbind(x,y,z,anom)) %>% mutate(anom = if_else(anom >= thresh, 'Anomaly', 'Normal') )


fig <- plot_ly(testdf, x = ~x, y = ~y, z = ~z, color = ~anom, colors = c('#BF382A', '#0C4B8E'))
fig <- fig %>% add_markers()
fig <- fig %>% layout(scene = list(xaxis = list(title = paste('PC1 ', info$importance[2]*100,"%")),
                     yaxis = list(title = paste('PC2 ', info$importance[5]*100,"%")),
                     zaxis = list(title = paste('PC3 ', info$importance[8]*100,"%"))
                     ))
fig
```


```{r}
library(ggfortify)


test <- prcomp(df[metrics])
info <-  summary(test)

info$importance
info$importance[2]

x <- as.vector(test[["x"]][,1])
y <- as.vector(test[["x"]][,2])
z <- as.vector(test[["x"]][,3])


anom <- as.vector(df$Anomaly_Label)

testdf <-  as.data.frame(cbind(x,y,z,anom))


fig <- plot_ly(testdf, x = ~x, y = ~y, z = ~z, color = ~anom, colors = c('#BF382A', '#0C4B8E'))
fig <- fig %>% add_markers()
fig <- fig %>% layout(scene = list(xaxis = list(title = paste('PC1 ', info$importance[2]*100,"%")),
                     yaxis = list(title = paste('PC2 ', info$importance[5]*100,"%")),
                     zaxis = list(title = paste('PC3 ', info$importance[8]*100,"%"))
                     ))
fig


fig1 <- plot_ly(testdf, x = ~x, y = ~y, color = ~anom, colors = c('#BF382A', '#0C4B8E'))

fig1

autoplot(prcomp(df[2:5]), data = df[2:7], colour = 'Anomaly_Label')



```

```{r}

library(Rtsne)
# perform dimensionality redcution to 2D
set.seed(123)
tsne <- Rtsne(LVN[1:4], dims = 2, check_duplicates = FALSE, perplexity=15, verbose=TRUE, max_iter = 500)

plot(tsne$Y, col = LVN$RESPONSE, pch = 19, cex=1.5)



# colors = rainbow(length(unique(df$Anomaly_Score)))
# names(colors) = unique(df$Anomaly_Score)
# par(mgp=c(2.5,1,0))
# plot(tsne$Y, t='n', main="tSNE", xlab="tSNE dimension 1", ylab="tSNE dimension 2", "cex.main"=2, "cex.lab"=1.5)
# text(tsne$Y, labels=df$Anomaly_Score, col=colors[df$Anomaly_Score])
# # display the results of t-SNE
# cols <- rainbow(10)
# plot(tsne$Y, t='n')
# text(tsne$Y, labels=df[,10])




```

```{r}



dfH2oTree = h2o.getModelTree(model = anomaly_classificationtree, tree_number = 1)

library(data.tree)

createDataTree <- function(h2oTree) {
  h2oTreeRoot = h2oTree@root_node
  dataTree = Node$new(h2oTreeRoot@split_feature)
  dataTree$type = 'split'
  addChildren(dataTree, h2oTreeRoot)
  return(dataTree)
}

addChildren <- function(dtree, node) {
  
  if(class(node)[1] != 'H2OSplitNode') return(TRUE)
  
  feature = node@split_feature
  id = node@id
  na_direction = node@na_direction
  
  if(is.na(node@threshold)) {
    leftEdgeLabel = printValues(node@left_levels, 
                                na_direction=='LEFT', 4)
    rightEdgeLabel = printValues(node@right_levels, 
                                 na_direction=='RIGHT', 4)
  }else {
    leftEdgeLabel = paste("<", node@threshold, 
                          ifelse(na_direction=='LEFT',',NA',''))
    rightEdgeLabel = paste(">=", node@threshold, 
                           ifelse(na_direction=='RIGHT',',NA',''))
  }
  
  left_node = node@left_child
  right_node = node@right_child
  
  if(class(left_node)[[1]] == 'H2OLeafNode')
    leftLabel = paste("prediction:", left_node@prediction)
  else
    leftLabel = left_node@split_feature
  
  if(class(right_node)[[1]] == 'H2OLeafNode')
    rightLabel = paste("prediction:", right_node@prediction)
  else
    rightLabel = right_node@split_feature
  
  if(leftLabel == rightLabel) {
    leftLabel = paste(leftLabel, "(L)")
    rightLabel = paste(rightLabel, "(R)")
  }
  
  dtreeLeft = dtree$AddChild(leftLabel)
  dtreeLeft$edgeLabel = leftEdgeLabel
  dtreeLeft$type = ifelse(class(left_node)[1] == 'H2OSplitNode', 'split', 'leaf')
  
  dtreeRight = dtree$AddChild(rightLabel)
  dtreeRight$edgeLabel = rightEdgeLabel
  dtreeRight$type = ifelse(class(right_node)[1] == 'H2OSplitNode', 'split', 'leaf')
  
  addChildren(dtreeLeft, left_node)
  addChildren(dtreeRight, right_node)
  
  return(FALSE)
}

printValues <- function(values, is_na_direction, n=4) {
  l = length(values)
  if(l == 0)
    value_string = ifelse(is_na_direction, "NA", "")
  else
    value_string = paste0(paste0(values[1:min(n,l)], collapse = ', '),
                          ifelse(l > n, ",...", ""),
                          ifelse(is_na_direction, ", NA", ""))
  return(value_string)
}

```


```{r}

dfTree = createDataTree(dfH2oTree)

GetEdgeLabel <- function(node) {return (node$edgeLabel)}
GetNodeShape <- function(node) {switch(node$type, 
                                       split = "diamond", leaf = "oval")}
GetFontName <- function(node) {switch(node$type, 
                                      split = 'Palatino-bold', 
                                      leaf = 'Palatino')}
SetEdgeStyle(dfTree, fontname = 'Palatino-italic', 
             label = GetEdgeLabel, labelfloat = TRUE,
             fontsize = "26", fontcolor='royalblue4')
SetNodeStyle(dfTree, fontname = GetFontName, shape = GetNodeShape, 
             fontsize = "26", fontcolor='royalblue4',
             height="0.75", width="1")

SetGraphStyle(dfTree, rankdir = "UD", dpi=70.)

plot(dfTree, output = "graph")


```