---
title: "Dev"
author: "Akshay Kulkarni"
date: "2/23/2020"
output: html_document
---


## R Markdown


```{r}
library(dplyr)


splitCombinedData  <-  function(inputdata, column, head_rows=5){
  if (class(inputdata$column) == "factor") {
    opts <- levels(inputdata$column)
  }
  else{
    opts <- inputdata %>% select(column) %>% distinct()
  }

  guide <- list()
  test <- list()
  i <- 1
  for (val in opts){
    guide[[i]] <- inputdata[inputdata$column == val, ][c(1:5), ]
    test[[i]] <- inputdata[inputdata$column == val, ][-c(1:5), ]
    i <- i+1
  }

  guide <- bind_rows(guide)
  test <-  bind_rows(test)
  
  print(guide)
  
  split_df <- list(guide, test)
  
  return(split_df)
}


test <- splitCombinedData(combined_data,"Precursor")
#########################

combined_data <-  read.csv("Datasets/Sampledata_CPTAC_Study_9_1_Site54 copy.csv")
opts <- levels(combined_data$"Precursor")
write.csv(
  bind_rows(
  lapply(opts, function(x) combined_data[combined_data$"Precursor" == x, ][c(1:5), ] ))
  ,"Sampledata_CPTAC_Study_9_1_Site54_GUIDE.csv")


write.csv(
  bind_rows(
  lapply(opts, function(x) combined_data[combined_data$"Precursor" == x, ][-c(1:5), ] ))
  ,"Sampledata_CPTAC_Study_9_1_Site54_TEST.csv")

```
```{r}
library(plotly)
library(dplyr)
library(tidyr)


source('src/QCMetrics.R')
source('src/ggradar.R')
source('src/helper-functions.R')


test <- read.csv("./Datasets/Sampledata_CPTAC_Study_9_1_Site54_GUIDE.csv", stringsAsFactors = T)


metrics <- c(find_custom_metrics(test))

peptides <- c(levels(test$Precursor))

dat2 <- test %>% filter(Precursor == peptides[[1]]) %>% mutate_at(metrics, ~(scale(., center = T) %>% as.vector)) 

dat3 <-  dat2 %>% select(Precursor,metrics) %>% pivot_longer(-Precursor, names_to = "Metric", values_to = "Value") 

temp <- test %>% select(Precursor,metrics) %>% pivot_longer(-Precursor, names_to = "Metric", values_to = "Value")

fig <- plot_ly(dat3, x = ~Metric, y = ~Value, color = ~Metric, type = "box")

fig

peptide_box.plot <- function(prodata, data.peptides, data.metrics, ret_obj_list = T) {
  plots <- list()
  for(i in seq_len(length(data.peptides))) {
    peptide <- data.peptides[i]
    
    data <- prodata %>% filter(Precursor == peptide) 
    
    data <-  data %>% mutate_at(data.metrics, ~(scale(., center = T) %>% as.vector)) 
    
    data <-  data %>% select(Precursor,data.metrics) %>% pivot_longer(-Precursor, names_to = "Metric", values_to = "Value") 
    
    plots[[i]] <- plot_ly(data, x = ~Metric, y = ~Value, color = ~Metric, type = "box") %>%
      layout(
        annotations = list(
          list(x = 0.5 , y = 1, text = peptide, showarrow = F, xref='paper', yref='paper')
        ),showlegend = FALSE)
  }
  
  if (ret_obj_list == F){
    height <- (length(data.peptides))*300
    p <- do.call(subplot,c(plots,nrows= floor(length(plots)/2))) %>%
      layout(autosize = TRUE, height = height,margin = unit(c(3, 1, 1, 1), "lines"))
    return(p)}
  else{
    return(plots)
  }
}


p <-  peptide_box.plot(test, peptides, metrics)


ggplotly(p[[1]])

```


```{r}

library(h2o)
h2o.init()


df <- read.csv("./Datasets/Sampledata_CPTAC_Study_9_1_Site54.csv")

# Import the prostate dataset
CPTAC_full <- h2o.importFile(path = "./Datasets/Sampledata_CPTAC_Study_9_1_Site54.csv",
                               destination_frame = "CPTAC_full")

# Split dataset giving the training dataset 75% of the data
CPTAC_split <- h2o.splitFrame(data=CPTAC_full, ratios=0.75)

# Create a training set from the 1st dataset in the split
train <- CPTAC_split[[1]]

# Create a testing set from the 2nd dataset in the split
test <- CPTAC_split[[2]]

# Build an Isolation forest model
seed = 12345
ntrees = 100

model <- h2o.isolationForest(training_frame=CPTAC_full,
                             sample_rate = 0.1,
                             max_depth = 20,
                             ntrees = 100)

# Calculate score
score_h2oObj <- h2o.predict(model, CPTAC_full)

score <-  as.data.frame(score_h2oObj)

result_pred <- score$predict

result_ml <- score$mean_length

head(score,20)

hist(result_ml)

qplot(result_pred, geom="histogram") 


conf <-  0.95

thresh <-  quantile(score$predict,0.95)

Outliers <- score[score$predict>thresh,]

Outliers1 <- score_h2oObj[score_h2oObj$predict>thresh,]

print(Outliers)

# Predict the leaf node assignment
ln_pred <- h2o.predict_leaf_node_assignment(model, test)


```



```{r}
library(anomalize) #tidy anomaly detectiom
library(tidyverse)


df <- read.csv("./Datasets/Sampledata_CPTAC_Study_9_1_Site54.csv")
df

df_ts <- df %>% as.tibble() %>% 
  mutate(date = as.POSIXct(AcquiredTime, format = "%m/%d/%y %H:%M")) %>% 
  # filter(Precursor == "LVNELTEFAK") %>% 
  # select(date,Best.RT)

df_ts %>% 
  time_decompose(Best.RT, method = "stl", frequency = "auto", trend = "auto") %>%
  anomalize(remainder, method = "gesd", alpha = 0.05, max_anoms = 0.2) %>%
  plot_anomaly_decomposition()

```
